### ISSUE TITLE
Cannot get reported experimental results by ecoflap_first.py

### ISSUE THREAD

**Issue by Wuzimeng** [ylsung/ECoFLaP#4] opened 2024-01-20 10:58 UTC
Hello, I tried to run `ecoflap_first.py`, but the eval results are much less than the reported values.
I noticed that the `sparsity_ratio_granularity` config is not added in `ecoflap_first.py`, thus the model is pruned with fixed sparsity 0.5. Then I added this config, but the results became even less. I wonder if there is any other modification I need to do with the code to regenerate the experimental results.
As for the difference of experimental results, take task `vqav2_zeroshot_flant5xl_eval` for example: 
1. with raw code `ecoflap_first.py`: 57.64   
2. with `sparsity_ratio_granularity` added as `block`: 54.56
3. reported in paper: **59.4**

Thanks a lot for your time.

**Comment by ylsung** [comment] 2024-01-29 16:36
Thank you for reporting the issue. I am rerunning the experiments and checking on it. Stay tune.

**Comment by ylsung** [comment] 2024-01-29 20:00
I reproduced the results and got `58.96` and `58.91` on two different machines and torch versions (`2.1.1` and `2.1.2`). In the paper, I used `torch==1.13.1`, so there is a small difference in the results but I think the number is reasonable. 

I just updated a newer version of the codes. Could you run the script again after pulling the latest code?

**Comment by ylsung** [comment] 2024-03-26 16:16
I will close the issue for now. Let me know if you still cannot reproduce the results.

**Closed as completed by ylsung** 2024-03-26 16:16 UTC
